language: java
jdk:
  - oraclejdk8
script: "mvn clean install"
after_success:
  - mvn clean test jacoco:report coveralls:jacoco
notifications:
  email:
    recipients:
      - aoxp-dev@googlegroups.com
